name: flutter_async_bloc
description: Flutter async common boilerplate using bloc pattern
version: 0.0.1
author: Haqqi <me@haqqi.net>
homepage: http://github.com/haqqi

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
